 name: Run CreateGCPFolderConnector Script
  env:
    SUBSCRIPTION_ID: "f2e26c0b-8b27-4edd-b6f4-73edc39a4186"
    TENANT_ID: "1172494f-68e2-4743-8ebb-b6916a1c681e"
    GCP_FOLDER_ID: "93604753456"
    GCP_ORGANIZATION_ID: "1044632980853"
    CLIENT_ID: "d47fb118-5c46-4069-801d-a7c945665e0f"
    CLIENT_SECRET: "NkG8Q~.FzKAZCNttyqvHxAwaeero5ciRepXKDa6Z"
    RESOURCE_GROUP: "kpmg-testing"
  run: |
    ./onboard_gcp_folder_test.ps1 `
      -SubscriptionId $env:SUBSCRIPTION_ID `
      -TenantId $env:TENANT_ID `
      -GCPFolderId $env:GCP_FOLDER_ID `
      -ClientId $env:CLIENT_ID `
      -ClientSecret $env:CLIENT_SECRET `
      -ResourceGroup $env:RESOURCE_GROUP `
      -ManagementProjectId "sbx-sentinel-mde-dev-920788" `
      -ManagementProjectNumber "1031194949050"
  shell: pwsh

- name: Upload final-body.json as Artifact
  uses: actions/upload-artifact@v4
  with:
    name: ConnectorJson
    path: final-body.json
